services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      # - /srv/nutshell/media/tv:/media/tv
      # - /srv/nutshell/media/movies:/media/movies
      - /srv/nutshell/media:/media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Karachi
      - WEBUI_PORT=4000
    volumes:
      - /srv/qbittorrent/config:/config
      - /srv/nutshell/torrents:/torrents
      - /srv/nutshell/media:/media

  torrentlab:
    image: ghcr.io/abdul-rehman-d/torrent-lab:latest
    container_name: torrentlab
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: "002"
      CONFIG_DIR: /config
      MOVIES_PATH: /media/movies
      TV_PATH: /media/tv
      INCOMPLETE_PATH: /torrents/incomplete
      DOWNLOADS_PATH: /torrents/downloads
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - /srv/torrentlab/config:/config
      - /srv/nutshell/torrents:/torrents
      - /srv/nutshell/media:/media
    depends_on:
      - qbittorrent
    restart: unless-stopped

